name: Build, Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    needs: []
    steps:
      - name: Checkout code
        id: checkout-code
        uses: actions/checkout@v2

      - name: Setup Go environment
        uses: actions/setup-go@v2
        with:
          go-version: ^1.14

      - name: Build all artifacts
        run: make build-all

      - name: Create release and upload artifacts
        id: upload-release-asset
        run: |
          set -x

          assets=()
          assets+=("-a" "./target/kubefire")
          assets+=("-a" "./target/kubefire.sha256")
          assets+=("-a" "./target/cni/host-local-rev")
          assets+=("-a" "./target/cni/host-local-rev.sha256")

          tag_name="${GITHUB_REF##*/}"
          hub release create -d "${assets[@]}" -m "$tag_name" "$tag_name"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
