name: Release kernel images

on:
  workflow_dispatch:
    inputs:

jobs:
  release:
    name: Release kernel images
    runs-on: ubuntu-latest
    needs: []
    steps:
      - name: Checkout code
        id: checkout-code
        uses: actions/checkout@v2

      - name: Release images
        run: make publish-kernels
        env:
          CR_USERNAME: ${{ secrets.CR_USERNAME }}
          CR_PAT: ${{ secrets.CR_PAT }}
          CR_PATH: ghcr.io/
